# Generated by Django 5.2 on 2025-06-27 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WatermarkedDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='documents/')),
                ('watermarked_document', models.FileField(blank=True, null=True, upload_to='watermarked_documents/')),
                ('watermark_text', models.CharField(max_length=255)),
                ('watermark_color', models.CharField(default='#fffffe', max_length=7)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
